app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path("", views.home, name='home'),
    path("app/addprofile/", views.addprofile, name='addprofile'),
    path("login/", views.login, name='login'),
    path("login/posts/", views.posts, name='posts')
]

insta/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('app.urls'))
]

app/models.py
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=255, blank=True)
    # profile_picture = models.ImageField(upload_to='profile_pictures', blank=True)
    website = models.URLField(max_length=255, blank=True)
    # created_at = models.DateTimeField(auto_now_add=True)


class Post(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    caption = models.CharField(max_length=255)
    # image = models.ImageField(upload_to='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    email = forms.EmailField(max_length=254, required=True, help_text='Required. Enter a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

app/views.py
from django.shortcuts import render
from .forms import UserForm,LoginForm
from app.models import Post, Comment


# Create your views here.

def home(request):
    return render(request, 'app/home.html')

def addprofile(request):
    form = UserForm()
    return render(request,'app/profile.html',{'form': form})

def login(request):
    form = UserForm()
    return render(request,'app/login.html',{'form': LoginForm})

def posts(request):
    post_list= Post.objects.all()
    comment_list=Comment.objects.all()
    return render(request,'app/posts.html',{'post_list': post_list,'comment_list': comment_list})

app/templates/app/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Instagram by Team3</title>
</head>
<body>
   <h1>Instagram by Team3</h1>
   <h2>New User, Create a profile</h2>
   <button><a href={% url 'app:addprofile' %}>Add Profile</a></button>
   <h2>Existing User, Login</h2>
   <button><a href="{% url 'app:login' %}">Login</a></button>
</body>
</html>

app/templates/app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login page</title>
</head>
<body>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
    <button class="btn btn-primary" type="submit" name="login"><a href="{% url 'app:posts' %}">Login</a></button>
    <button class="btn btn-secondary" type="submit" name="return"><a href={% url 'app:home' %}>Home page</a></button>
</form>
</body>
</html>

app/templates/app/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Posts of the User</h1>
 {% for post in post_list %}
       <li>{{ post.caption }}</li>
       <ol>
        {% for comment in comment_list %}
            {% if post == comment.post %}
                <li>{{ comment.text }}</li>
            {% endif %}
           {% endfor %}
       </ol>
   {% endfor %}
<button><a href={% url 'app:home' %}>Home page</a></button>
</body>
</html>

app/templates/app/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Profile</title>
</head>
<body>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Register</button>
    <button><a href={% url 'app:home' %}>Home page</a></button>
    <button><a href="{% url 'app:login' %}">Login</a></button>
</form>
</body>
</html>